apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-stage
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/vinothbaskaran1312-jpg/java-maven-app-gitops.git
    targetRevision: main
    path: .
    helm:
      valueFiles:
        - values-stage.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: helm-stage

  syncPolicy:
    automated:
      prune: true
      selfHeal: true